package com.cxdaiweb.account.systemmessage.model;

import java.util.Date;

public class CashrecordLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cashrecord_log.ID
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cashrecord_log.CASHRECORD_ID
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    private Integer cashrecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cashrecord_log.TYPE
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cashrecord_log.ADDTIME
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cashrecord_log.ADDIP
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    private String addip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cashrecord_log.ADDUSER
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    private Integer adduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cashrecord_log.DEVICE_SN
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    private String deviceSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cashrecord_log.PLATFORM
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    private Integer platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cashrecord_log.REMARK
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cashrecord_log.ID
     *
     * @return the value of t_cashrecord_log.ID
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cashrecord_log.ID
     *
     * @param id the value for t_cashrecord_log.ID
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cashrecord_log.CASHRECORD_ID
     *
     * @return the value of t_cashrecord_log.CASHRECORD_ID
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public Integer getCashrecordId() {
        return cashrecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cashrecord_log.CASHRECORD_ID
     *
     * @param cashrecordId the value for t_cashrecord_log.CASHRECORD_ID
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public void setCashrecordId(Integer cashrecordId) {
        this.cashrecordId = cashrecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cashrecord_log.TYPE
     *
     * @return the value of t_cashrecord_log.TYPE
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cashrecord_log.TYPE
     *
     * @param type the value for t_cashrecord_log.TYPE
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cashrecord_log.ADDTIME
     *
     * @return the value of t_cashrecord_log.ADDTIME
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cashrecord_log.ADDTIME
     *
     * @param addtime the value for t_cashrecord_log.ADDTIME
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cashrecord_log.ADDIP
     *
     * @return the value of t_cashrecord_log.ADDIP
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public String getAddip() {
        return addip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cashrecord_log.ADDIP
     *
     * @param addip the value for t_cashrecord_log.ADDIP
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public void setAddip(String addip) {
        this.addip = addip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cashrecord_log.ADDUSER
     *
     * @return the value of t_cashrecord_log.ADDUSER
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public Integer getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cashrecord_log.ADDUSER
     *
     * @param adduser the value for t_cashrecord_log.ADDUSER
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public void setAdduser(Integer adduser) {
        this.adduser = adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cashrecord_log.DEVICE_SN
     *
     * @return the value of t_cashrecord_log.DEVICE_SN
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public String getDeviceSn() {
        return deviceSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cashrecord_log.DEVICE_SN
     *
     * @param deviceSn the value for t_cashrecord_log.DEVICE_SN
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public void setDeviceSn(String deviceSn) {
        this.deviceSn = deviceSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cashrecord_log.PLATFORM
     *
     * @return the value of t_cashrecord_log.PLATFORM
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cashrecord_log.PLATFORM
     *
     * @param platform the value for t_cashrecord_log.PLATFORM
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cashrecord_log.REMARK
     *
     * @return the value of t_cashrecord_log.REMARK
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cashrecord_log.REMARK
     *
     * @param remark the value for t_cashrecord_log.REMARK
     *
     * @mbggenerated Mon Feb 29 10:04:59 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}