package com.cxdaiweb.account.systemmessage.model;

import java.math.BigDecimal;
import java.util.Date;

public class Cur {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.ID
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.NAME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.STATUS
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.PLAN_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private BigDecimal planAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.ACCOUNT_YES
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private BigDecimal accountYes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.INVEST_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private BigDecimal investAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.REINVEST_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private BigDecimal reinvestAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.LOWEST_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private BigDecimal lowestAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.MOST_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private BigDecimal mostAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.APR
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private BigDecimal apr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.SUCCESS_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Date successTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.VALID_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Integer validTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.END_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.CONTENT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.ADDTIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.ADDIP
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private String addip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.ADDUSER
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Integer adduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.LAST_MODIFY_USER
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Integer lastModifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.LAST_MODIFY_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.LAST_MODIFY_REMARK
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private String lastModifyRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.CONTRACT_NO
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private String contractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.BID_PASSWORD
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private String bidPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.IS_AUTOTENDER
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Integer isAutotender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.REMARK
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.PUBLISH_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.TENDER_TIMES
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Integer tenderTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.INVEST_TIMES
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Integer investTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.REINVEST_TIMES
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Integer reinvestTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.AREA_TYPE
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Integer areaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cur.AREA_CHANGE_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    private Date areaChangeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.ID
     *
     * @return the value of t_cur.ID
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.ID
     *
     * @param id the value for t_cur.ID
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.NAME
     *
     * @return the value of t_cur.NAME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.NAME
     *
     * @param name the value for t_cur.NAME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.STATUS
     *
     * @return the value of t_cur.STATUS
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.STATUS
     *
     * @param status the value for t_cur.STATUS
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.PLAN_ACCOUNT
     *
     * @return the value of t_cur.PLAN_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public BigDecimal getPlanAccount() {
        return planAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.PLAN_ACCOUNT
     *
     * @param planAccount the value for t_cur.PLAN_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setPlanAccount(BigDecimal planAccount) {
        this.planAccount = planAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.ACCOUNT_YES
     *
     * @return the value of t_cur.ACCOUNT_YES
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public BigDecimal getAccountYes() {
        return accountYes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.ACCOUNT_YES
     *
     * @param accountYes the value for t_cur.ACCOUNT_YES
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setAccountYes(BigDecimal accountYes) {
        this.accountYes = accountYes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.INVEST_ACCOUNT
     *
     * @return the value of t_cur.INVEST_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public BigDecimal getInvestAccount() {
        return investAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.INVEST_ACCOUNT
     *
     * @param investAccount the value for t_cur.INVEST_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setInvestAccount(BigDecimal investAccount) {
        this.investAccount = investAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.REINVEST_ACCOUNT
     *
     * @return the value of t_cur.REINVEST_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public BigDecimal getReinvestAccount() {
        return reinvestAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.REINVEST_ACCOUNT
     *
     * @param reinvestAccount the value for t_cur.REINVEST_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setReinvestAccount(BigDecimal reinvestAccount) {
        this.reinvestAccount = reinvestAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.LOWEST_ACCOUNT
     *
     * @return the value of t_cur.LOWEST_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public BigDecimal getLowestAccount() {
        return lowestAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.LOWEST_ACCOUNT
     *
     * @param lowestAccount the value for t_cur.LOWEST_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setLowestAccount(BigDecimal lowestAccount) {
        this.lowestAccount = lowestAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.MOST_ACCOUNT
     *
     * @return the value of t_cur.MOST_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public BigDecimal getMostAccount() {
        return mostAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.MOST_ACCOUNT
     *
     * @param mostAccount the value for t_cur.MOST_ACCOUNT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setMostAccount(BigDecimal mostAccount) {
        this.mostAccount = mostAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.APR
     *
     * @return the value of t_cur.APR
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public BigDecimal getApr() {
        return apr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.APR
     *
     * @param apr the value for t_cur.APR
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setApr(BigDecimal apr) {
        this.apr = apr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.SUCCESS_TIME
     *
     * @return the value of t_cur.SUCCESS_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Date getSuccessTime() {
        return successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.SUCCESS_TIME
     *
     * @param successTime the value for t_cur.SUCCESS_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setSuccessTime(Date successTime) {
        this.successTime = successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.VALID_TIME
     *
     * @return the value of t_cur.VALID_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Integer getValidTime() {
        return validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.VALID_TIME
     *
     * @param validTime the value for t_cur.VALID_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setValidTime(Integer validTime) {
        this.validTime = validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.END_TIME
     *
     * @return the value of t_cur.END_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.END_TIME
     *
     * @param endTime the value for t_cur.END_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.CONTENT
     *
     * @return the value of t_cur.CONTENT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.CONTENT
     *
     * @param content the value for t_cur.CONTENT
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.ADDTIME
     *
     * @return the value of t_cur.ADDTIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.ADDTIME
     *
     * @param addtime the value for t_cur.ADDTIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.ADDIP
     *
     * @return the value of t_cur.ADDIP
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public String getAddip() {
        return addip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.ADDIP
     *
     * @param addip the value for t_cur.ADDIP
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setAddip(String addip) {
        this.addip = addip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.ADDUSER
     *
     * @return the value of t_cur.ADDUSER
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Integer getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.ADDUSER
     *
     * @param adduser the value for t_cur.ADDUSER
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setAdduser(Integer adduser) {
        this.adduser = adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.LAST_MODIFY_USER
     *
     * @return the value of t_cur.LAST_MODIFY_USER
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Integer getLastModifyUser() {
        return lastModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.LAST_MODIFY_USER
     *
     * @param lastModifyUser the value for t_cur.LAST_MODIFY_USER
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setLastModifyUser(Integer lastModifyUser) {
        this.lastModifyUser = lastModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.LAST_MODIFY_TIME
     *
     * @return the value of t_cur.LAST_MODIFY_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.LAST_MODIFY_TIME
     *
     * @param lastModifyTime the value for t_cur.LAST_MODIFY_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.LAST_MODIFY_REMARK
     *
     * @return the value of t_cur.LAST_MODIFY_REMARK
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public String getLastModifyRemark() {
        return lastModifyRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.LAST_MODIFY_REMARK
     *
     * @param lastModifyRemark the value for t_cur.LAST_MODIFY_REMARK
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setLastModifyRemark(String lastModifyRemark) {
        this.lastModifyRemark = lastModifyRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.CONTRACT_NO
     *
     * @return the value of t_cur.CONTRACT_NO
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.CONTRACT_NO
     *
     * @param contractNo the value for t_cur.CONTRACT_NO
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.BID_PASSWORD
     *
     * @return the value of t_cur.BID_PASSWORD
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public String getBidPassword() {
        return bidPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.BID_PASSWORD
     *
     * @param bidPassword the value for t_cur.BID_PASSWORD
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setBidPassword(String bidPassword) {
        this.bidPassword = bidPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.IS_AUTOTENDER
     *
     * @return the value of t_cur.IS_AUTOTENDER
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Integer getIsAutotender() {
        return isAutotender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.IS_AUTOTENDER
     *
     * @param isAutotender the value for t_cur.IS_AUTOTENDER
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setIsAutotender(Integer isAutotender) {
        this.isAutotender = isAutotender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.REMARK
     *
     * @return the value of t_cur.REMARK
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.REMARK
     *
     * @param remark the value for t_cur.REMARK
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.PUBLISH_TIME
     *
     * @return the value of t_cur.PUBLISH_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.PUBLISH_TIME
     *
     * @param publishTime the value for t_cur.PUBLISH_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.TENDER_TIMES
     *
     * @return the value of t_cur.TENDER_TIMES
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Integer getTenderTimes() {
        return tenderTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.TENDER_TIMES
     *
     * @param tenderTimes the value for t_cur.TENDER_TIMES
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setTenderTimes(Integer tenderTimes) {
        this.tenderTimes = tenderTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.INVEST_TIMES
     *
     * @return the value of t_cur.INVEST_TIMES
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Integer getInvestTimes() {
        return investTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.INVEST_TIMES
     *
     * @param investTimes the value for t_cur.INVEST_TIMES
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setInvestTimes(Integer investTimes) {
        this.investTimes = investTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.REINVEST_TIMES
     *
     * @return the value of t_cur.REINVEST_TIMES
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Integer getReinvestTimes() {
        return reinvestTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.REINVEST_TIMES
     *
     * @param reinvestTimes the value for t_cur.REINVEST_TIMES
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setReinvestTimes(Integer reinvestTimes) {
        this.reinvestTimes = reinvestTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.AREA_TYPE
     *
     * @return the value of t_cur.AREA_TYPE
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Integer getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.AREA_TYPE
     *
     * @param areaType the value for t_cur.AREA_TYPE
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setAreaType(Integer areaType) {
        this.areaType = areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cur.AREA_CHANGE_TIME
     *
     * @return the value of t_cur.AREA_CHANGE_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Date getAreaChangeTime() {
        return areaChangeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cur.AREA_CHANGE_TIME
     *
     * @param areaChangeTime the value for t_cur.AREA_CHANGE_TIME
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setAreaChangeTime(Date areaChangeTime) {
        this.areaChangeTime = areaChangeTime;
    }
}