package com.cxdaiweb.account.systemmessage.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CurExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public CurExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andPlanAccountIsNull() {
            addCriterion("PLAN_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andPlanAccountIsNotNull() {
            addCriterion("PLAN_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andPlanAccountEqualTo(BigDecimal value) {
            addCriterion("PLAN_ACCOUNT =", value, "planAccount");
            return (Criteria) this;
        }

        public Criteria andPlanAccountNotEqualTo(BigDecimal value) {
            addCriterion("PLAN_ACCOUNT <>", value, "planAccount");
            return (Criteria) this;
        }

        public Criteria andPlanAccountGreaterThan(BigDecimal value) {
            addCriterion("PLAN_ACCOUNT >", value, "planAccount");
            return (Criteria) this;
        }

        public Criteria andPlanAccountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PLAN_ACCOUNT >=", value, "planAccount");
            return (Criteria) this;
        }

        public Criteria andPlanAccountLessThan(BigDecimal value) {
            addCriterion("PLAN_ACCOUNT <", value, "planAccount");
            return (Criteria) this;
        }

        public Criteria andPlanAccountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PLAN_ACCOUNT <=", value, "planAccount");
            return (Criteria) this;
        }

        public Criteria andPlanAccountIn(List<BigDecimal> values) {
            addCriterion("PLAN_ACCOUNT in", values, "planAccount");
            return (Criteria) this;
        }

        public Criteria andPlanAccountNotIn(List<BigDecimal> values) {
            addCriterion("PLAN_ACCOUNT not in", values, "planAccount");
            return (Criteria) this;
        }

        public Criteria andPlanAccountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PLAN_ACCOUNT between", value1, value2, "planAccount");
            return (Criteria) this;
        }

        public Criteria andPlanAccountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PLAN_ACCOUNT not between", value1, value2, "planAccount");
            return (Criteria) this;
        }

        public Criteria andAccountYesIsNull() {
            addCriterion("ACCOUNT_YES is null");
            return (Criteria) this;
        }

        public Criteria andAccountYesIsNotNull() {
            addCriterion("ACCOUNT_YES is not null");
            return (Criteria) this;
        }

        public Criteria andAccountYesEqualTo(BigDecimal value) {
            addCriterion("ACCOUNT_YES =", value, "accountYes");
            return (Criteria) this;
        }

        public Criteria andAccountYesNotEqualTo(BigDecimal value) {
            addCriterion("ACCOUNT_YES <>", value, "accountYes");
            return (Criteria) this;
        }

        public Criteria andAccountYesGreaterThan(BigDecimal value) {
            addCriterion("ACCOUNT_YES >", value, "accountYes");
            return (Criteria) this;
        }

        public Criteria andAccountYesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACCOUNT_YES >=", value, "accountYes");
            return (Criteria) this;
        }

        public Criteria andAccountYesLessThan(BigDecimal value) {
            addCriterion("ACCOUNT_YES <", value, "accountYes");
            return (Criteria) this;
        }

        public Criteria andAccountYesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACCOUNT_YES <=", value, "accountYes");
            return (Criteria) this;
        }

        public Criteria andAccountYesIn(List<BigDecimal> values) {
            addCriterion("ACCOUNT_YES in", values, "accountYes");
            return (Criteria) this;
        }

        public Criteria andAccountYesNotIn(List<BigDecimal> values) {
            addCriterion("ACCOUNT_YES not in", values, "accountYes");
            return (Criteria) this;
        }

        public Criteria andAccountYesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACCOUNT_YES between", value1, value2, "accountYes");
            return (Criteria) this;
        }

        public Criteria andAccountYesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACCOUNT_YES not between", value1, value2, "accountYes");
            return (Criteria) this;
        }

        public Criteria andInvestAccountIsNull() {
            addCriterion("INVEST_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andInvestAccountIsNotNull() {
            addCriterion("INVEST_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andInvestAccountEqualTo(BigDecimal value) {
            addCriterion("INVEST_ACCOUNT =", value, "investAccount");
            return (Criteria) this;
        }

        public Criteria andInvestAccountNotEqualTo(BigDecimal value) {
            addCriterion("INVEST_ACCOUNT <>", value, "investAccount");
            return (Criteria) this;
        }

        public Criteria andInvestAccountGreaterThan(BigDecimal value) {
            addCriterion("INVEST_ACCOUNT >", value, "investAccount");
            return (Criteria) this;
        }

        public Criteria andInvestAccountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INVEST_ACCOUNT >=", value, "investAccount");
            return (Criteria) this;
        }

        public Criteria andInvestAccountLessThan(BigDecimal value) {
            addCriterion("INVEST_ACCOUNT <", value, "investAccount");
            return (Criteria) this;
        }

        public Criteria andInvestAccountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INVEST_ACCOUNT <=", value, "investAccount");
            return (Criteria) this;
        }

        public Criteria andInvestAccountIn(List<BigDecimal> values) {
            addCriterion("INVEST_ACCOUNT in", values, "investAccount");
            return (Criteria) this;
        }

        public Criteria andInvestAccountNotIn(List<BigDecimal> values) {
            addCriterion("INVEST_ACCOUNT not in", values, "investAccount");
            return (Criteria) this;
        }

        public Criteria andInvestAccountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INVEST_ACCOUNT between", value1, value2, "investAccount");
            return (Criteria) this;
        }

        public Criteria andInvestAccountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INVEST_ACCOUNT not between", value1, value2, "investAccount");
            return (Criteria) this;
        }

        public Criteria andReinvestAccountIsNull() {
            addCriterion("REINVEST_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andReinvestAccountIsNotNull() {
            addCriterion("REINVEST_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andReinvestAccountEqualTo(BigDecimal value) {
            addCriterion("REINVEST_ACCOUNT =", value, "reinvestAccount");
            return (Criteria) this;
        }

        public Criteria andReinvestAccountNotEqualTo(BigDecimal value) {
            addCriterion("REINVEST_ACCOUNT <>", value, "reinvestAccount");
            return (Criteria) this;
        }

        public Criteria andReinvestAccountGreaterThan(BigDecimal value) {
            addCriterion("REINVEST_ACCOUNT >", value, "reinvestAccount");
            return (Criteria) this;
        }

        public Criteria andReinvestAccountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REINVEST_ACCOUNT >=", value, "reinvestAccount");
            return (Criteria) this;
        }

        public Criteria andReinvestAccountLessThan(BigDecimal value) {
            addCriterion("REINVEST_ACCOUNT <", value, "reinvestAccount");
            return (Criteria) this;
        }

        public Criteria andReinvestAccountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REINVEST_ACCOUNT <=", value, "reinvestAccount");
            return (Criteria) this;
        }

        public Criteria andReinvestAccountIn(List<BigDecimal> values) {
            addCriterion("REINVEST_ACCOUNT in", values, "reinvestAccount");
            return (Criteria) this;
        }

        public Criteria andReinvestAccountNotIn(List<BigDecimal> values) {
            addCriterion("REINVEST_ACCOUNT not in", values, "reinvestAccount");
            return (Criteria) this;
        }

        public Criteria andReinvestAccountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REINVEST_ACCOUNT between", value1, value2, "reinvestAccount");
            return (Criteria) this;
        }

        public Criteria andReinvestAccountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REINVEST_ACCOUNT not between", value1, value2, "reinvestAccount");
            return (Criteria) this;
        }

        public Criteria andLowestAccountIsNull() {
            addCriterion("LOWEST_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andLowestAccountIsNotNull() {
            addCriterion("LOWEST_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andLowestAccountEqualTo(BigDecimal value) {
            addCriterion("LOWEST_ACCOUNT =", value, "lowestAccount");
            return (Criteria) this;
        }

        public Criteria andLowestAccountNotEqualTo(BigDecimal value) {
            addCriterion("LOWEST_ACCOUNT <>", value, "lowestAccount");
            return (Criteria) this;
        }

        public Criteria andLowestAccountGreaterThan(BigDecimal value) {
            addCriterion("LOWEST_ACCOUNT >", value, "lowestAccount");
            return (Criteria) this;
        }

        public Criteria andLowestAccountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LOWEST_ACCOUNT >=", value, "lowestAccount");
            return (Criteria) this;
        }

        public Criteria andLowestAccountLessThan(BigDecimal value) {
            addCriterion("LOWEST_ACCOUNT <", value, "lowestAccount");
            return (Criteria) this;
        }

        public Criteria andLowestAccountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LOWEST_ACCOUNT <=", value, "lowestAccount");
            return (Criteria) this;
        }

        public Criteria andLowestAccountIn(List<BigDecimal> values) {
            addCriterion("LOWEST_ACCOUNT in", values, "lowestAccount");
            return (Criteria) this;
        }

        public Criteria andLowestAccountNotIn(List<BigDecimal> values) {
            addCriterion("LOWEST_ACCOUNT not in", values, "lowestAccount");
            return (Criteria) this;
        }

        public Criteria andLowestAccountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOWEST_ACCOUNT between", value1, value2, "lowestAccount");
            return (Criteria) this;
        }

        public Criteria andLowestAccountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOWEST_ACCOUNT not between", value1, value2, "lowestAccount");
            return (Criteria) this;
        }

        public Criteria andMostAccountIsNull() {
            addCriterion("MOST_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andMostAccountIsNotNull() {
            addCriterion("MOST_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andMostAccountEqualTo(BigDecimal value) {
            addCriterion("MOST_ACCOUNT =", value, "mostAccount");
            return (Criteria) this;
        }

        public Criteria andMostAccountNotEqualTo(BigDecimal value) {
            addCriterion("MOST_ACCOUNT <>", value, "mostAccount");
            return (Criteria) this;
        }

        public Criteria andMostAccountGreaterThan(BigDecimal value) {
            addCriterion("MOST_ACCOUNT >", value, "mostAccount");
            return (Criteria) this;
        }

        public Criteria andMostAccountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MOST_ACCOUNT >=", value, "mostAccount");
            return (Criteria) this;
        }

        public Criteria andMostAccountLessThan(BigDecimal value) {
            addCriterion("MOST_ACCOUNT <", value, "mostAccount");
            return (Criteria) this;
        }

        public Criteria andMostAccountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MOST_ACCOUNT <=", value, "mostAccount");
            return (Criteria) this;
        }

        public Criteria andMostAccountIn(List<BigDecimal> values) {
            addCriterion("MOST_ACCOUNT in", values, "mostAccount");
            return (Criteria) this;
        }

        public Criteria andMostAccountNotIn(List<BigDecimal> values) {
            addCriterion("MOST_ACCOUNT not in", values, "mostAccount");
            return (Criteria) this;
        }

        public Criteria andMostAccountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MOST_ACCOUNT between", value1, value2, "mostAccount");
            return (Criteria) this;
        }

        public Criteria andMostAccountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MOST_ACCOUNT not between", value1, value2, "mostAccount");
            return (Criteria) this;
        }

        public Criteria andAprIsNull() {
            addCriterion("APR is null");
            return (Criteria) this;
        }

        public Criteria andAprIsNotNull() {
            addCriterion("APR is not null");
            return (Criteria) this;
        }

        public Criteria andAprEqualTo(BigDecimal value) {
            addCriterion("APR =", value, "apr");
            return (Criteria) this;
        }

        public Criteria andAprNotEqualTo(BigDecimal value) {
            addCriterion("APR <>", value, "apr");
            return (Criteria) this;
        }

        public Criteria andAprGreaterThan(BigDecimal value) {
            addCriterion("APR >", value, "apr");
            return (Criteria) this;
        }

        public Criteria andAprGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("APR >=", value, "apr");
            return (Criteria) this;
        }

        public Criteria andAprLessThan(BigDecimal value) {
            addCriterion("APR <", value, "apr");
            return (Criteria) this;
        }

        public Criteria andAprLessThanOrEqualTo(BigDecimal value) {
            addCriterion("APR <=", value, "apr");
            return (Criteria) this;
        }

        public Criteria andAprIn(List<BigDecimal> values) {
            addCriterion("APR in", values, "apr");
            return (Criteria) this;
        }

        public Criteria andAprNotIn(List<BigDecimal> values) {
            addCriterion("APR not in", values, "apr");
            return (Criteria) this;
        }

        public Criteria andAprBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("APR between", value1, value2, "apr");
            return (Criteria) this;
        }

        public Criteria andAprNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("APR not between", value1, value2, "apr");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeIsNull() {
            addCriterion("SUCCESS_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeIsNotNull() {
            addCriterion("SUCCESS_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeEqualTo(Date value) {
            addCriterion("SUCCESS_TIME =", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeNotEqualTo(Date value) {
            addCriterion("SUCCESS_TIME <>", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeGreaterThan(Date value) {
            addCriterion("SUCCESS_TIME >", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SUCCESS_TIME >=", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeLessThan(Date value) {
            addCriterion("SUCCESS_TIME <", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeLessThanOrEqualTo(Date value) {
            addCriterion("SUCCESS_TIME <=", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeIn(List<Date> values) {
            addCriterion("SUCCESS_TIME in", values, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeNotIn(List<Date> values) {
            addCriterion("SUCCESS_TIME not in", values, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeBetween(Date value1, Date value2) {
            addCriterion("SUCCESS_TIME between", value1, value2, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeNotBetween(Date value1, Date value2) {
            addCriterion("SUCCESS_TIME not between", value1, value2, "successTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeIsNull() {
            addCriterion("VALID_TIME is null");
            return (Criteria) this;
        }

        public Criteria andValidTimeIsNotNull() {
            addCriterion("VALID_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andValidTimeEqualTo(Integer value) {
            addCriterion("VALID_TIME =", value, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeNotEqualTo(Integer value) {
            addCriterion("VALID_TIME <>", value, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeGreaterThan(Integer value) {
            addCriterion("VALID_TIME >", value, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("VALID_TIME >=", value, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeLessThan(Integer value) {
            addCriterion("VALID_TIME <", value, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeLessThanOrEqualTo(Integer value) {
            addCriterion("VALID_TIME <=", value, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeIn(List<Integer> values) {
            addCriterion("VALID_TIME in", values, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeNotIn(List<Integer> values) {
            addCriterion("VALID_TIME not in", values, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeBetween(Integer value1, Integer value2) {
            addCriterion("VALID_TIME between", value1, value2, "validTime");
            return (Criteria) this;
        }

        public Criteria andValidTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("VALID_TIME not between", value1, value2, "validTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("END_TIME =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("END_TIME <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("END_TIME >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("END_TIME >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("END_TIME <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("END_TIME <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("END_TIME in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("END_TIME not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("END_TIME between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("END_TIME not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("CONTENT =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("CONTENT <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("CONTENT >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("CONTENT >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("CONTENT <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("CONTENT <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("CONTENT like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("CONTENT not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("CONTENT in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("CONTENT not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("CONTENT between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("CONTENT not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNull() {
            addCriterion("ADDTIME is null");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNotNull() {
            addCriterion("ADDTIME is not null");
            return (Criteria) this;
        }

        public Criteria andAddtimeEqualTo(Date value) {
            addCriterion("ADDTIME =", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotEqualTo(Date value) {
            addCriterion("ADDTIME <>", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThan(Date value) {
            addCriterion("ADDTIME >", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADDTIME >=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThan(Date value) {
            addCriterion("ADDTIME <", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThanOrEqualTo(Date value) {
            addCriterion("ADDTIME <=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeIn(List<Date> values) {
            addCriterion("ADDTIME in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotIn(List<Date> values) {
            addCriterion("ADDTIME not in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeBetween(Date value1, Date value2) {
            addCriterion("ADDTIME between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotBetween(Date value1, Date value2) {
            addCriterion("ADDTIME not between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddipIsNull() {
            addCriterion("ADDIP is null");
            return (Criteria) this;
        }

        public Criteria andAddipIsNotNull() {
            addCriterion("ADDIP is not null");
            return (Criteria) this;
        }

        public Criteria andAddipEqualTo(String value) {
            addCriterion("ADDIP =", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipNotEqualTo(String value) {
            addCriterion("ADDIP <>", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipGreaterThan(String value) {
            addCriterion("ADDIP >", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipGreaterThanOrEqualTo(String value) {
            addCriterion("ADDIP >=", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipLessThan(String value) {
            addCriterion("ADDIP <", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipLessThanOrEqualTo(String value) {
            addCriterion("ADDIP <=", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipLike(String value) {
            addCriterion("ADDIP like", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipNotLike(String value) {
            addCriterion("ADDIP not like", value, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipIn(List<String> values) {
            addCriterion("ADDIP in", values, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipNotIn(List<String> values) {
            addCriterion("ADDIP not in", values, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipBetween(String value1, String value2) {
            addCriterion("ADDIP between", value1, value2, "addip");
            return (Criteria) this;
        }

        public Criteria andAddipNotBetween(String value1, String value2) {
            addCriterion("ADDIP not between", value1, value2, "addip");
            return (Criteria) this;
        }

        public Criteria andAdduserIsNull() {
            addCriterion("ADDUSER is null");
            return (Criteria) this;
        }

        public Criteria andAdduserIsNotNull() {
            addCriterion("ADDUSER is not null");
            return (Criteria) this;
        }

        public Criteria andAdduserEqualTo(Integer value) {
            addCriterion("ADDUSER =", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserNotEqualTo(Integer value) {
            addCriterion("ADDUSER <>", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserGreaterThan(Integer value) {
            addCriterion("ADDUSER >", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserGreaterThanOrEqualTo(Integer value) {
            addCriterion("ADDUSER >=", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserLessThan(Integer value) {
            addCriterion("ADDUSER <", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserLessThanOrEqualTo(Integer value) {
            addCriterion("ADDUSER <=", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserIn(List<Integer> values) {
            addCriterion("ADDUSER in", values, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserNotIn(List<Integer> values) {
            addCriterion("ADDUSER not in", values, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserBetween(Integer value1, Integer value2) {
            addCriterion("ADDUSER between", value1, value2, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserNotBetween(Integer value1, Integer value2) {
            addCriterion("ADDUSER not between", value1, value2, "adduser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIsNull() {
            addCriterion("LAST_MODIFY_USER is null");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIsNotNull() {
            addCriterion("LAST_MODIFY_USER is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserEqualTo(Integer value) {
            addCriterion("LAST_MODIFY_USER =", value, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserNotEqualTo(Integer value) {
            addCriterion("LAST_MODIFY_USER <>", value, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserGreaterThan(Integer value) {
            addCriterion("LAST_MODIFY_USER >", value, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("LAST_MODIFY_USER >=", value, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserLessThan(Integer value) {
            addCriterion("LAST_MODIFY_USER <", value, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserLessThanOrEqualTo(Integer value) {
            addCriterion("LAST_MODIFY_USER <=", value, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIn(List<Integer> values) {
            addCriterion("LAST_MODIFY_USER in", values, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserNotIn(List<Integer> values) {
            addCriterion("LAST_MODIFY_USER not in", values, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserBetween(Integer value1, Integer value2) {
            addCriterion("LAST_MODIFY_USER between", value1, value2, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserNotBetween(Integer value1, Integer value2) {
            addCriterion("LAST_MODIFY_USER not between", value1, value2, "lastModifyUser");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNull() {
            addCriterion("LAST_MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNotNull() {
            addCriterion("LAST_MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeEqualTo(Date value) {
            addCriterion("LAST_MODIFY_TIME =", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotEqualTo(Date value) {
            addCriterion("LAST_MODIFY_TIME <>", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThan(Date value) {
            addCriterion("LAST_MODIFY_TIME >", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_MODIFY_TIME >=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThan(Date value) {
            addCriterion("LAST_MODIFY_TIME <", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_MODIFY_TIME <=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIn(List<Date> values) {
            addCriterion("LAST_MODIFY_TIME in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotIn(List<Date> values) {
            addCriterion("LAST_MODIFY_TIME not in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeBetween(Date value1, Date value2) {
            addCriterion("LAST_MODIFY_TIME between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_MODIFY_TIME not between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyRemarkIsNull() {
            addCriterion("LAST_MODIFY_REMARK is null");
            return (Criteria) this;
        }

        public Criteria andLastModifyRemarkIsNotNull() {
            addCriterion("LAST_MODIFY_REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifyRemarkEqualTo(String value) {
            addCriterion("LAST_MODIFY_REMARK =", value, "lastModifyRemark");
            return (Criteria) this;
        }

        public Criteria andLastModifyRemarkNotEqualTo(String value) {
            addCriterion("LAST_MODIFY_REMARK <>", value, "lastModifyRemark");
            return (Criteria) this;
        }

        public Criteria andLastModifyRemarkGreaterThan(String value) {
            addCriterion("LAST_MODIFY_REMARK >", value, "lastModifyRemark");
            return (Criteria) this;
        }

        public Criteria andLastModifyRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_MODIFY_REMARK >=", value, "lastModifyRemark");
            return (Criteria) this;
        }

        public Criteria andLastModifyRemarkLessThan(String value) {
            addCriterion("LAST_MODIFY_REMARK <", value, "lastModifyRemark");
            return (Criteria) this;
        }

        public Criteria andLastModifyRemarkLessThanOrEqualTo(String value) {
            addCriterion("LAST_MODIFY_REMARK <=", value, "lastModifyRemark");
            return (Criteria) this;
        }

        public Criteria andLastModifyRemarkLike(String value) {
            addCriterion("LAST_MODIFY_REMARK like", value, "lastModifyRemark");
            return (Criteria) this;
        }

        public Criteria andLastModifyRemarkNotLike(String value) {
            addCriterion("LAST_MODIFY_REMARK not like", value, "lastModifyRemark");
            return (Criteria) this;
        }

        public Criteria andLastModifyRemarkIn(List<String> values) {
            addCriterion("LAST_MODIFY_REMARK in", values, "lastModifyRemark");
            return (Criteria) this;
        }

        public Criteria andLastModifyRemarkNotIn(List<String> values) {
            addCriterion("LAST_MODIFY_REMARK not in", values, "lastModifyRemark");
            return (Criteria) this;
        }

        public Criteria andLastModifyRemarkBetween(String value1, String value2) {
            addCriterion("LAST_MODIFY_REMARK between", value1, value2, "lastModifyRemark");
            return (Criteria) this;
        }

        public Criteria andLastModifyRemarkNotBetween(String value1, String value2) {
            addCriterion("LAST_MODIFY_REMARK not between", value1, value2, "lastModifyRemark");
            return (Criteria) this;
        }

        public Criteria andContractNoIsNull() {
            addCriterion("CONTRACT_NO is null");
            return (Criteria) this;
        }

        public Criteria andContractNoIsNotNull() {
            addCriterion("CONTRACT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andContractNoEqualTo(String value) {
            addCriterion("CONTRACT_NO =", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotEqualTo(String value) {
            addCriterion("CONTRACT_NO <>", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoGreaterThan(String value) {
            addCriterion("CONTRACT_NO >", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoGreaterThanOrEqualTo(String value) {
            addCriterion("CONTRACT_NO >=", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLessThan(String value) {
            addCriterion("CONTRACT_NO <", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLessThanOrEqualTo(String value) {
            addCriterion("CONTRACT_NO <=", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLike(String value) {
            addCriterion("CONTRACT_NO like", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotLike(String value) {
            addCriterion("CONTRACT_NO not like", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoIn(List<String> values) {
            addCriterion("CONTRACT_NO in", values, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotIn(List<String> values) {
            addCriterion("CONTRACT_NO not in", values, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoBetween(String value1, String value2) {
            addCriterion("CONTRACT_NO between", value1, value2, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotBetween(String value1, String value2) {
            addCriterion("CONTRACT_NO not between", value1, value2, "contractNo");
            return (Criteria) this;
        }

        public Criteria andBidPasswordIsNull() {
            addCriterion("BID_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andBidPasswordIsNotNull() {
            addCriterion("BID_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andBidPasswordEqualTo(String value) {
            addCriterion("BID_PASSWORD =", value, "bidPassword");
            return (Criteria) this;
        }

        public Criteria andBidPasswordNotEqualTo(String value) {
            addCriterion("BID_PASSWORD <>", value, "bidPassword");
            return (Criteria) this;
        }

        public Criteria andBidPasswordGreaterThan(String value) {
            addCriterion("BID_PASSWORD >", value, "bidPassword");
            return (Criteria) this;
        }

        public Criteria andBidPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("BID_PASSWORD >=", value, "bidPassword");
            return (Criteria) this;
        }

        public Criteria andBidPasswordLessThan(String value) {
            addCriterion("BID_PASSWORD <", value, "bidPassword");
            return (Criteria) this;
        }

        public Criteria andBidPasswordLessThanOrEqualTo(String value) {
            addCriterion("BID_PASSWORD <=", value, "bidPassword");
            return (Criteria) this;
        }

        public Criteria andBidPasswordLike(String value) {
            addCriterion("BID_PASSWORD like", value, "bidPassword");
            return (Criteria) this;
        }

        public Criteria andBidPasswordNotLike(String value) {
            addCriterion("BID_PASSWORD not like", value, "bidPassword");
            return (Criteria) this;
        }

        public Criteria andBidPasswordIn(List<String> values) {
            addCriterion("BID_PASSWORD in", values, "bidPassword");
            return (Criteria) this;
        }

        public Criteria andBidPasswordNotIn(List<String> values) {
            addCriterion("BID_PASSWORD not in", values, "bidPassword");
            return (Criteria) this;
        }

        public Criteria andBidPasswordBetween(String value1, String value2) {
            addCriterion("BID_PASSWORD between", value1, value2, "bidPassword");
            return (Criteria) this;
        }

        public Criteria andBidPasswordNotBetween(String value1, String value2) {
            addCriterion("BID_PASSWORD not between", value1, value2, "bidPassword");
            return (Criteria) this;
        }

        public Criteria andIsAutotenderIsNull() {
            addCriterion("IS_AUTOTENDER is null");
            return (Criteria) this;
        }

        public Criteria andIsAutotenderIsNotNull() {
            addCriterion("IS_AUTOTENDER is not null");
            return (Criteria) this;
        }

        public Criteria andIsAutotenderEqualTo(Integer value) {
            addCriterion("IS_AUTOTENDER =", value, "isAutotender");
            return (Criteria) this;
        }

        public Criteria andIsAutotenderNotEqualTo(Integer value) {
            addCriterion("IS_AUTOTENDER <>", value, "isAutotender");
            return (Criteria) this;
        }

        public Criteria andIsAutotenderGreaterThan(Integer value) {
            addCriterion("IS_AUTOTENDER >", value, "isAutotender");
            return (Criteria) this;
        }

        public Criteria andIsAutotenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_AUTOTENDER >=", value, "isAutotender");
            return (Criteria) this;
        }

        public Criteria andIsAutotenderLessThan(Integer value) {
            addCriterion("IS_AUTOTENDER <", value, "isAutotender");
            return (Criteria) this;
        }

        public Criteria andIsAutotenderLessThanOrEqualTo(Integer value) {
            addCriterion("IS_AUTOTENDER <=", value, "isAutotender");
            return (Criteria) this;
        }

        public Criteria andIsAutotenderIn(List<Integer> values) {
            addCriterion("IS_AUTOTENDER in", values, "isAutotender");
            return (Criteria) this;
        }

        public Criteria andIsAutotenderNotIn(List<Integer> values) {
            addCriterion("IS_AUTOTENDER not in", values, "isAutotender");
            return (Criteria) this;
        }

        public Criteria andIsAutotenderBetween(Integer value1, Integer value2) {
            addCriterion("IS_AUTOTENDER between", value1, value2, "isAutotender");
            return (Criteria) this;
        }

        public Criteria andIsAutotenderNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_AUTOTENDER not between", value1, value2, "isAutotender");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIsNull() {
            addCriterion("PUBLISH_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIsNotNull() {
            addCriterion("PUBLISH_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPublishTimeEqualTo(Date value) {
            addCriterion("PUBLISH_TIME =", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotEqualTo(Date value) {
            addCriterion("PUBLISH_TIME <>", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeGreaterThan(Date value) {
            addCriterion("PUBLISH_TIME >", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PUBLISH_TIME >=", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeLessThan(Date value) {
            addCriterion("PUBLISH_TIME <", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeLessThanOrEqualTo(Date value) {
            addCriterion("PUBLISH_TIME <=", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIn(List<Date> values) {
            addCriterion("PUBLISH_TIME in", values, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotIn(List<Date> values) {
            addCriterion("PUBLISH_TIME not in", values, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeBetween(Date value1, Date value2) {
            addCriterion("PUBLISH_TIME between", value1, value2, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotBetween(Date value1, Date value2) {
            addCriterion("PUBLISH_TIME not between", value1, value2, "publishTime");
            return (Criteria) this;
        }

        public Criteria andTenderTimesIsNull() {
            addCriterion("TENDER_TIMES is null");
            return (Criteria) this;
        }

        public Criteria andTenderTimesIsNotNull() {
            addCriterion("TENDER_TIMES is not null");
            return (Criteria) this;
        }

        public Criteria andTenderTimesEqualTo(Integer value) {
            addCriterion("TENDER_TIMES =", value, "tenderTimes");
            return (Criteria) this;
        }

        public Criteria andTenderTimesNotEqualTo(Integer value) {
            addCriterion("TENDER_TIMES <>", value, "tenderTimes");
            return (Criteria) this;
        }

        public Criteria andTenderTimesGreaterThan(Integer value) {
            addCriterion("TENDER_TIMES >", value, "tenderTimes");
            return (Criteria) this;
        }

        public Criteria andTenderTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("TENDER_TIMES >=", value, "tenderTimes");
            return (Criteria) this;
        }

        public Criteria andTenderTimesLessThan(Integer value) {
            addCriterion("TENDER_TIMES <", value, "tenderTimes");
            return (Criteria) this;
        }

        public Criteria andTenderTimesLessThanOrEqualTo(Integer value) {
            addCriterion("TENDER_TIMES <=", value, "tenderTimes");
            return (Criteria) this;
        }

        public Criteria andTenderTimesIn(List<Integer> values) {
            addCriterion("TENDER_TIMES in", values, "tenderTimes");
            return (Criteria) this;
        }

        public Criteria andTenderTimesNotIn(List<Integer> values) {
            addCriterion("TENDER_TIMES not in", values, "tenderTimes");
            return (Criteria) this;
        }

        public Criteria andTenderTimesBetween(Integer value1, Integer value2) {
            addCriterion("TENDER_TIMES between", value1, value2, "tenderTimes");
            return (Criteria) this;
        }

        public Criteria andTenderTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("TENDER_TIMES not between", value1, value2, "tenderTimes");
            return (Criteria) this;
        }

        public Criteria andInvestTimesIsNull() {
            addCriterion("INVEST_TIMES is null");
            return (Criteria) this;
        }

        public Criteria andInvestTimesIsNotNull() {
            addCriterion("INVEST_TIMES is not null");
            return (Criteria) this;
        }

        public Criteria andInvestTimesEqualTo(Integer value) {
            addCriterion("INVEST_TIMES =", value, "investTimes");
            return (Criteria) this;
        }

        public Criteria andInvestTimesNotEqualTo(Integer value) {
            addCriterion("INVEST_TIMES <>", value, "investTimes");
            return (Criteria) this;
        }

        public Criteria andInvestTimesGreaterThan(Integer value) {
            addCriterion("INVEST_TIMES >", value, "investTimes");
            return (Criteria) this;
        }

        public Criteria andInvestTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("INVEST_TIMES >=", value, "investTimes");
            return (Criteria) this;
        }

        public Criteria andInvestTimesLessThan(Integer value) {
            addCriterion("INVEST_TIMES <", value, "investTimes");
            return (Criteria) this;
        }

        public Criteria andInvestTimesLessThanOrEqualTo(Integer value) {
            addCriterion("INVEST_TIMES <=", value, "investTimes");
            return (Criteria) this;
        }

        public Criteria andInvestTimesIn(List<Integer> values) {
            addCriterion("INVEST_TIMES in", values, "investTimes");
            return (Criteria) this;
        }

        public Criteria andInvestTimesNotIn(List<Integer> values) {
            addCriterion("INVEST_TIMES not in", values, "investTimes");
            return (Criteria) this;
        }

        public Criteria andInvestTimesBetween(Integer value1, Integer value2) {
            addCriterion("INVEST_TIMES between", value1, value2, "investTimes");
            return (Criteria) this;
        }

        public Criteria andInvestTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("INVEST_TIMES not between", value1, value2, "investTimes");
            return (Criteria) this;
        }

        public Criteria andReinvestTimesIsNull() {
            addCriterion("REINVEST_TIMES is null");
            return (Criteria) this;
        }

        public Criteria andReinvestTimesIsNotNull() {
            addCriterion("REINVEST_TIMES is not null");
            return (Criteria) this;
        }

        public Criteria andReinvestTimesEqualTo(Integer value) {
            addCriterion("REINVEST_TIMES =", value, "reinvestTimes");
            return (Criteria) this;
        }

        public Criteria andReinvestTimesNotEqualTo(Integer value) {
            addCriterion("REINVEST_TIMES <>", value, "reinvestTimes");
            return (Criteria) this;
        }

        public Criteria andReinvestTimesGreaterThan(Integer value) {
            addCriterion("REINVEST_TIMES >", value, "reinvestTimes");
            return (Criteria) this;
        }

        public Criteria andReinvestTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("REINVEST_TIMES >=", value, "reinvestTimes");
            return (Criteria) this;
        }

        public Criteria andReinvestTimesLessThan(Integer value) {
            addCriterion("REINVEST_TIMES <", value, "reinvestTimes");
            return (Criteria) this;
        }

        public Criteria andReinvestTimesLessThanOrEqualTo(Integer value) {
            addCriterion("REINVEST_TIMES <=", value, "reinvestTimes");
            return (Criteria) this;
        }

        public Criteria andReinvestTimesIn(List<Integer> values) {
            addCriterion("REINVEST_TIMES in", values, "reinvestTimes");
            return (Criteria) this;
        }

        public Criteria andReinvestTimesNotIn(List<Integer> values) {
            addCriterion("REINVEST_TIMES not in", values, "reinvestTimes");
            return (Criteria) this;
        }

        public Criteria andReinvestTimesBetween(Integer value1, Integer value2) {
            addCriterion("REINVEST_TIMES between", value1, value2, "reinvestTimes");
            return (Criteria) this;
        }

        public Criteria andReinvestTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("REINVEST_TIMES not between", value1, value2, "reinvestTimes");
            return (Criteria) this;
        }

        public Criteria andAreaTypeIsNull() {
            addCriterion("AREA_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andAreaTypeIsNotNull() {
            addCriterion("AREA_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAreaTypeEqualTo(Integer value) {
            addCriterion("AREA_TYPE =", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeNotEqualTo(Integer value) {
            addCriterion("AREA_TYPE <>", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeGreaterThan(Integer value) {
            addCriterion("AREA_TYPE >", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("AREA_TYPE >=", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeLessThan(Integer value) {
            addCriterion("AREA_TYPE <", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeLessThanOrEqualTo(Integer value) {
            addCriterion("AREA_TYPE <=", value, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeIn(List<Integer> values) {
            addCriterion("AREA_TYPE in", values, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeNotIn(List<Integer> values) {
            addCriterion("AREA_TYPE not in", values, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeBetween(Integer value1, Integer value2) {
            addCriterion("AREA_TYPE between", value1, value2, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("AREA_TYPE not between", value1, value2, "areaType");
            return (Criteria) this;
        }

        public Criteria andAreaChangeTimeIsNull() {
            addCriterion("AREA_CHANGE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andAreaChangeTimeIsNotNull() {
            addCriterion("AREA_CHANGE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andAreaChangeTimeEqualTo(Date value) {
            addCriterion("AREA_CHANGE_TIME =", value, "areaChangeTime");
            return (Criteria) this;
        }

        public Criteria andAreaChangeTimeNotEqualTo(Date value) {
            addCriterion("AREA_CHANGE_TIME <>", value, "areaChangeTime");
            return (Criteria) this;
        }

        public Criteria andAreaChangeTimeGreaterThan(Date value) {
            addCriterion("AREA_CHANGE_TIME >", value, "areaChangeTime");
            return (Criteria) this;
        }

        public Criteria andAreaChangeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("AREA_CHANGE_TIME >=", value, "areaChangeTime");
            return (Criteria) this;
        }

        public Criteria andAreaChangeTimeLessThan(Date value) {
            addCriterion("AREA_CHANGE_TIME <", value, "areaChangeTime");
            return (Criteria) this;
        }

        public Criteria andAreaChangeTimeLessThanOrEqualTo(Date value) {
            addCriterion("AREA_CHANGE_TIME <=", value, "areaChangeTime");
            return (Criteria) this;
        }

        public Criteria andAreaChangeTimeIn(List<Date> values) {
            addCriterion("AREA_CHANGE_TIME in", values, "areaChangeTime");
            return (Criteria) this;
        }

        public Criteria andAreaChangeTimeNotIn(List<Date> values) {
            addCriterion("AREA_CHANGE_TIME not in", values, "areaChangeTime");
            return (Criteria) this;
        }

        public Criteria andAreaChangeTimeBetween(Date value1, Date value2) {
            addCriterion("AREA_CHANGE_TIME between", value1, value2, "areaChangeTime");
            return (Criteria) this;
        }

        public Criteria andAreaChangeTimeNotBetween(Date value1, Date value2) {
            addCriterion("AREA_CHANGE_TIME not between", value1, value2, "areaChangeTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cur
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 23 15:05:38 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}