package com.cxdaiweb.account.systemmessage.model;

import com.cxdaiweb.account.systemmessage.model.Cur;
import com.cxdaiweb.account.systemmessage.model.CurExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CurMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    int countByExample(CurExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    int deleteByExample(CurExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    int insert(Cur record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    int insertSelective(Cur record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    List<Cur> selectByExample(CurExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    Cur selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") Cur record, @Param("example") CurExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    int updateByExample(@Param("record") Cur record, @Param("example") CurExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    int updateByPrimaryKeySelective(Cur record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cur
     *
     * @mbggenerated Tue Feb 23 15:05:38 CST 2016
     */
    int updateByPrimaryKey(Cur record);
}