package com.cxdaiweb.account.systemmessage.model;

import java.util.Date;

public class MemberLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_log.ID
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_log.USER_ID
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_log.OPERATE_TYPE
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    private Integer operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_log.TARGET_TYPE
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    private Integer targetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_log.TARGET_ID
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    private Integer targetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_log.ADDUSER
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    private Integer adduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_log.ADDTIME
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_log.ADDIP
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    private String addip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_log.ADDMAC
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    private String addmac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_log.DEVICE_SN
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    private String deviceSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_log.REMARK
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_log.ID
     *
     * @return the value of t_member_log.ID
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_log.ID
     *
     * @param id the value for t_member_log.ID
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_log.USER_ID
     *
     * @return the value of t_member_log.USER_ID
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_log.USER_ID
     *
     * @param userId the value for t_member_log.USER_ID
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_log.OPERATE_TYPE
     *
     * @return the value of t_member_log.OPERATE_TYPE
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public Integer getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_log.OPERATE_TYPE
     *
     * @param operateType the value for t_member_log.OPERATE_TYPE
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_log.TARGET_TYPE
     *
     * @return the value of t_member_log.TARGET_TYPE
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public Integer getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_log.TARGET_TYPE
     *
     * @param targetType the value for t_member_log.TARGET_TYPE
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_log.TARGET_ID
     *
     * @return the value of t_member_log.TARGET_ID
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public Integer getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_log.TARGET_ID
     *
     * @param targetId the value for t_member_log.TARGET_ID
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_log.ADDUSER
     *
     * @return the value of t_member_log.ADDUSER
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public Integer getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_log.ADDUSER
     *
     * @param adduser the value for t_member_log.ADDUSER
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public void setAdduser(Integer adduser) {
        this.adduser = adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_log.ADDTIME
     *
     * @return the value of t_member_log.ADDTIME
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_log.ADDTIME
     *
     * @param addtime the value for t_member_log.ADDTIME
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_log.ADDIP
     *
     * @return the value of t_member_log.ADDIP
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public String getAddip() {
        return addip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_log.ADDIP
     *
     * @param addip the value for t_member_log.ADDIP
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public void setAddip(String addip) {
        this.addip = addip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_log.ADDMAC
     *
     * @return the value of t_member_log.ADDMAC
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public String getAddmac() {
        return addmac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_log.ADDMAC
     *
     * @param addmac the value for t_member_log.ADDMAC
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public void setAddmac(String addmac) {
        this.addmac = addmac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_log.DEVICE_SN
     *
     * @return the value of t_member_log.DEVICE_SN
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public String getDeviceSn() {
        return deviceSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_log.DEVICE_SN
     *
     * @param deviceSn the value for t_member_log.DEVICE_SN
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public void setDeviceSn(String deviceSn) {
        this.deviceSn = deviceSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_log.REMARK
     *
     * @return the value of t_member_log.REMARK
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_log.REMARK
     *
     * @param remark the value for t_member_log.REMARK
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}