package com.cxdaiweb.account.systemmessage.model;

import com.cxdaiweb.account.systemmessage.model.MemberLog;
import com.cxdaiweb.account.systemmessage.model.MemberLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_log
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    int countByExample(MemberLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_log
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    int deleteByExample(MemberLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_log
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_log
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    int insert(MemberLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_log
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    int insertSelective(MemberLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_log
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    List<MemberLog> selectByExample(MemberLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_log
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    MemberLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_log
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") MemberLog record, @Param("example") MemberLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_log
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    int updateByExample(@Param("record") MemberLog record, @Param("example") MemberLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_log
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    int updateByPrimaryKeySelective(MemberLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_log
     *
     * @mbggenerated Wed Mar 02 17:29:48 CST 2016
     */
    int updateByPrimaryKey(MemberLog record);
}